### PR TITLE
updated relations

### PR DESCRIPTION
**Pull request by thea-m**
https://github.com/BetaMasaheft/Documentation/issues/1920

### CODE REVIEW

**Comment by thea-m** [comment]
@DenisNosnitsin1970 @eu-genia

**Review by eu-genia — APPROVED** [review]

**Comment by thea-m** [comment]
Can this be merged?

**Comment by duncdrum** [comment]
@eu-genia there seem to have been accidental changes on the `master` branch. Can you rebase the pr on `master`?

**Comment by duncdrum** [comment]
@thea-m @eu-genia actually this is a bit more complex, since the PR predates the new workflow.  I will recreate this PR in-line with the new hotness.

**Comment by eu-genia** [comment]
I think with the new workflow it might be best to create a new branch from master and take over only the changes to the ODD, to avoid RNG conflicts

**Comment by eu-genia** [comment]
exactly this is what I was writing) a new PR from master is needed

**Comment by eu-genia** [comment]
I can do it

**Pull request closed without merging**
