### PR TITLE
ODD chaining and generation of schemas in CI 

### PR DESCRIPTION
**Pull request by HelenaSabel**
Overview:
- `tei-betamesaeft-expanded.xml` is now defined as derived from `tei-betamesaheft.xml`. This means that changes in the main ODD file will be automatically included in the expanded version.
- `tei-betamesaeft.xml` is now associated with the `tei_odds` customisation (instead of `tei_all`). The ODD was invalid against this schema and thus a minor update was carried out (mostly, it concerned the update of the scheme value from `isoschematron` to `schematron` and there were some `<sequence>` elements with just one child: no major corrections were implemented).
- Continuous integration adoption: each time a change of the ODD files is commited, the RELAXNG schemas are generated automatically. This means that the RELAXNG files no longer need to be commited by the contributors. The ODD files are also automatically validated against the  `tei_odds` schema.

### CODE REVIEW

**Review by duncdrum — CHANGES_REQUESTED** [review]
@HelenaSabel overall great stuff. I pushed some minor fixups to the packaging after checking the contents of the xar, and prevented the ci to start an infinite loop. 

Two areas need more work. 1) The Readme needs a bit more information. 2) the `tei-expanded.rng` currently looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<!-- *********************************************************************************************************** -->
<!-- *********************************************************************************************************** -->
<error msg="The requested initial template main does not exist" exclass="class pl.psnc.dl.ege.exception.ConverterException" >pl.psnc.dl.ege.exception.ConverterException: The requested initial template main does not exist
	at pl.psnc.dl.ege.MultiXslConverter.convert(MultiXslConverter.java:109)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:46)
	at java.base/java.lang.Thread.run(Thread.java:829)
</error>

<!-- *********************************************************************************************************** -->
<!-- *********************************************************************************************************** -->
```

This wasn't caught by our CI so I added two tests to catch that moving forward, they also caught an error in `tei-betamesaheft.xml` 

I believe the last correct version of the expanded rng happened [here](https://github.com/BetaMasaheft/Schema/actions/runs/6331544828/job/17196313574)

**Comment by HelenaSabel** [comment]
Thank you as always for your detailed reviews @duncdrum!

The duplicated `@xml:id` are not a problem: they are always inside different `<exemplum>` elements: that’s why the ODDs are valid against the TEI schema.

Concerning the generation of the expanded version, the error was created because TEI Garage couldn’t resolve the `@source` attribute. The transformation is now slightly different and it works (the build still fails when committing, but before that all steps are run).

Concerning the TEI version, it prevails: because that’s the version declared in the ODD, during the compilation the source is gotten from there. Thus, the ODDs themselves are being validated against the most recent released version of the `tei_odss` schema (which makes sense, because it is important to have any improvements there that then are translated into a more efficient RELANX transformation). However, the schemas produced for the project respond to whatever is defined in the ODD. I will leave a note about this in the documentation.

**Review by duncdrum — APPROVED** [review]
@HelenaSabel please have a look at my last changes. The missing piece was [artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts). The reports are now available to download from the GH guide, stored for 90 days. No need to mess with the repo contents. Lastly, to avoid having GHA produce an update after every pushed commit, we only commit to the main branch after a PR is merged. 

@eu-genia this PR relies on schema editors to follow the documented practice of working with branches and Pull requests. No committing to `master` directly.

**Comment by duncdrum** [comment]
@eu-genia merging this PR will trigger an automatic update to your schemas, and subsequently their deployment on the production server via the old git sync. Please have a look if you feel comfortable with this and a ready to merge. If you have any questions about how this impacts your workflows, or the contents of the updated schemas please ask, so we can add more documentation and make sure your editors don't feel spooked. 

In essence, implementing odd chaining, validating odds, and automating the update process should prevent the kind of drift between base and expanded that was present, as well as lower the time required for maintaining schema and authoring schema changes.

**Comment by eu-genia** [comment]
This looks like a great improvement! Thank you!
I am not quite sure though: the readme.md describes the manual procedure for transforming xml to rng (oXygen or teigarage, as we had been doing) - which could the circumstances be in which this is needed now if the transformation happens automatically on merge?

**Comment by HelenaSabel** [comment]
Hi @eu-genia! That section is there in case someone wants to reproduce locally the same tasks that take place in CI. The most likely target for that information is someone outside of the Beta maṣāḥǝft project interested in adapting your ODDs to create their own schemas (in particular the `tei-betamesaeft-expanded.xml ` one which already seems to be targeted to a broader audience?). 

Another circumstance in which that information could be useful is for local tests before suggesting an update: Maybe one of the collaborators wants to create the schema first to check if the results of a particular update are the ones they expect before committing the changes. The collaborators of the Beta maṣāḥǝft project won’t ever need to generate the schemas manually, but the information there is helpful in case they want to.

**Review by eu-genia — APPROVED** [review]
Thank you!

**Comment by eu-genia** [comment]
Just to remind that since September 2024 the CI generation has not been functioning - is there a chance it will be back? Or can it be completely disabled so that we do not get error messages every time? I would also then update the guidelines for the team to remember to generate rng in Oxygen

**Pull request merged**
